name: "Postgres Branching - Reset"
description: "Resets a preview database branch from its parent inside the same PostgreSQL instance"

inputs:
  branch_name:
    description: "Preview database branch name to reset"
    required: true
  parent_branch:
    description: "Parent database branch to restore from"
    required: true
  app_db_user:
    description: "Optional DB role to grant privileges on preview DB"
    required: false
    default: ""
  clone_strategy:
    description: "Clone client strategy: auto, local, or docker"
    required: false
    default: "auto"
  pg_host:
    description: "PostgreSQL host"
    required: true
  pg_port:
    description: "PostgreSQL port"
    required: true
  pg_user:
    description: "PostgreSQL user"
    required: true
  pg_password:
    description: "PostgreSQL password"
    required: true
  pg_database:
    description: "Administrative database for control operations"
    required: false
    default: "postgres"

outputs:
  preview_db:
    description: "Resolved preview DB name"
    value: ${{ steps.run.outputs.preview_db }}

runs:
  using: "composite"
  steps:
    - id: run
      shell: bash
      env:
        BRANCH_NAME: ${{ inputs.branch_name }}
        PARENT_BRANCH: ${{ inputs.parent_branch }}
        APP_DB_USER: ${{ inputs.app_db_user }}
        CLONE_STRATEGY: ${{ inputs.clone_strategy }}
        PGHOST: ${{ inputs.pg_host }}
        PGPORT: ${{ inputs.pg_port }}
        PGUSER: ${{ inputs.pg_user }}
        PGPASSWORD: ${{ inputs.pg_password }}
        PGDATABASE: ${{ inputs.pg_database }}
      run: |
        set -euo pipefail
        chmod +x "$GITHUB_ACTION_PATH/../scripts/preview-branch.sh"
        "$GITHUB_ACTION_PATH/../scripts/preview-branch.sh" reset
        echo "preview_db=${BRANCH_NAME}" >> "$GITHUB_OUTPUT"
